# Assignment 1 - NumPy
---

## Exercise 1: Array Creation

**You can only use NumPy's built-in array creation methods to answer the below questions.**

### 1.1

Import NumPY.

In [103]:
# 1.1 Answer
import numpy as np

### 1.2

Create a 1D array of ODD numbers between 1 and 15 (inclusive).

In [104]:
# 1.2 Answer
arr_odd = np.array([1,3,5,7,9,11,13,15])
print(arr_odd)

[ 1  3  5  7  9 11 13 15]


### 1.2

Create a 1D array of EVEN numbers between 0 and -20 (inclusive).

In [105]:
# 1.2 Answer
arr_even = np.array([-20,-18,-16,-14,-12,-10,-8,-6,-4,-2,0])
print(arr_even)

[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0]


### 1.3

Create an array of 7 ones. Make sure all the elements are integers, not floats.

In [106]:
# 1.3 Answer
arr_one = np.ones(7).astype(int)
print(arr_one)

[1 1 1 1 1 1 1]


### 1.4

Create an array of 7 eights. Make sure all the elements are integers, not floats.

In [107]:
# 1.4 Answer
arr_eight = np.ones(7)*8
arr_eight = arr_eight.astype(int)
print(arr_eight)

[8 8 8 8 8 8 8]


### 1.5

Create a 2D array of integers from -5 to -50. 

In [108]:
# 1.5 Answer
arr2 = np.random.randint(-50,-5,(3,4))
print(arr2)

[[-23 -13 -23 -21]
 [-48 -45 -39 -14]
 [-16 -50 -27 -14]]


### 1.6

Create an array of 5 random numbers between 0 and 1.

In [109]:
# 1.6
arr3 = np.random.rand(5)
print(arr3)

[0.48595378 0.59046327 0.17517879 0.6706378  0.95459941]


### 1.7

Create an array of 30 random numbers from a standard normal distribution.

In [110]:
# 1.7
arr4 = np.random.randn(30)
print(arr4)

[ 1.19422353  0.46685285  0.27995161  0.48109412  1.37174647 -0.22948147
 -0.63337078  0.93792711  0.17644436 -2.21384656 -1.16051332  0.4563469
  1.43207275 -0.03731316 -1.1145858  -1.41416528 -1.04885646 -0.60650423
  0.98768767  0.73527294 -1.75030031 -0.0830572  -0.92314272  0.61921048
 -1.18433667  0.75240397 -1.22815327 -0.02938918  0.64814639 -2.06588146]


### 1.8

Recreate the following array:

    array([[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9]],

           [[10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]]])


In [111]:
# 1.8 Answer
arrr = np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[10,11,12],
           [13,14,15],
           [16,17,18]]])

print(arrr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


### 1.9 

Create an array of 8 evenly spaced numbers between 0 and 1 (inclusive).

In [112]:
# 1.9 Answer
arr_spaced = np.linspace(0,1,8)
print(arr_spaced)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


## Exercise 2: Indexing and Selection

**Make sure your run the below cell. This is the array you will be working with.**

In [113]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 2.1

Select the numbers 29 and 30 from the array.

Your output should look like this:
    
    array([29, 30])

In [114]:
# 2.1 Answer
arr[-1,-2:]

array([29, 30])

### 2.2

Select the number 13 from the array.

In [115]:
# 2.2 Answer
arr[2,2]

13

### 2.3

Select the numbers 14, 19, and 24 from the array.

Your output should look like this:

    array([[14],
           [19],
           [24]])

In [116]:
# 2.3 Answer
arr[2:5,3:4]

array([[14],
       [19],
       [24]])

### 2.4

Write a code that produces the following output:

    array([[21, 22, 23, 24, 25],
           [26, 27, 28, 29, 30]])

In [117]:
# 2.4 Answer
arr[-2:]

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### 2.5

Write a code that produces the following output:

    array([[ 3,  4],
           [ 8,  9],
           [13, 14],
           [18, 19],
           [23, 24],
           [28, 29]])

In [118]:
# 2.5 Answer
arr[:,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29]])

## Exercise 3: More NumPy!

**Make sure your run the below cell. This is the array you will be working with.**

**You can only use NumPy's built-in array creation methods to answer the below questions.**

In [119]:
arr = np.arange(5,101,5).reshape(5,4)
arr

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

### 3.1

What is the sum of the values in arr?

In [120]:
# 3.1 Answer
print(f'The sum of the values in arr is : {arr.sum()}')

The sum of the values in arr is : 1050


### 3.2

What is the sum of values of each row in arr?

In [121]:
arr

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [122]:
# 3.2 Answer
for row in range(5):
    print("The sum of row {} is : {}".format(row + 1,arr[row,:].sum()))

The sum of row 1 is : 50
The sum of row 2 is : 130
The sum of row 3 is : 210
The sum of row 4 is : 290
The sum of row 5 is : 370


### 3.3

What is the min value in each column?

In [123]:
arr[:,0].min()

5

In [124]:
arr

array([[  5,  10,  15,  20],
       [ 25,  30,  35,  40],
       [ 45,  50,  55,  60],
       [ 65,  70,  75,  80],
       [ 85,  90,  95, 100]])

In [125]:
# 3.3 Answer
for column in range(4):
    print("The min value of column {} is : {}".format(column + 1,arr[:,column].min()))

The min value of column 1 is : 5
The min value of column 2 is : 10
The min value of column 3 is : 15
The min value of column 4 is : 20


### 3.4

Convert the rows in arr into columns, and the columns into rows.

Hint: Your new array should have a different shape.

In [126]:
# 3.4 Answer
arr_transposed = arr.transpose()
arr_transposed

array([[  5,  25,  45,  65,  85],
       [ 10,  30,  50,  70,  90],
       [ 15,  35,  55,  75,  95],
       [ 20,  40,  60,  80, 100]])

### 3.5

What is the square root of all the elements in arr?

In [127]:
# 3.5 Answer
arr_squareroot = np.sqrt(arr)
print(arr_squareroot)

[[ 2.23606798  3.16227766  3.87298335  4.47213595]
 [ 5.          5.47722558  5.91607978  6.32455532]
 [ 6.70820393  7.07106781  7.41619849  7.74596669]
 [ 8.06225775  8.36660027  8.66025404  8.94427191]
 [ 9.21954446  9.48683298  9.74679434 10.        ]]


## Bonus Question

Create a 4x4 identity matrix that matches this array:

    array([[0, 0, 0, 0],
           [1, 0, 0, 0],
           [0, 1, 0, 0],
           [0, 0, 1, 0]])
       
Pay attention to the location of the diagonal ones, as well as the data type of the above array.

[Click here for a hint.](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)

In [128]:
np.array([[0,0,0,1],[0,0,0,0],[0,0,0,0],[0,0,0,0]])

array([[0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [129]:
# Method 1:
identity4 = np.eye(4, dtype=int)
new = np.roll(identity4, 1, axis=0)
arr_help = np.array([[0,0,0,1],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
print(np.subtract(new,arr_help))

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [130]:
# Method 2:
arr1 = np.eye(4,dtype = int)
arr2 = np.array([[1,0,0,0],[-1,1,0,0],[0,-1,1,0],[0,0,-1,1]])
print(np.subtract(arr1,arr2))

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


# The End!